language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - sudo apt-get install cmake

# test script
script:
  - ctest -VV --output-on-failure .

# Notify the mailing list
notifications:
  email:
    on_success: change
    on_failure: always
